FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/excalidraw-fe ./apps/excalidraw-fe

RUN pnpm install
RUN pnpm build

CMD ["pnpm", "run", "start:fe"]

