name: Continuous Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.be
          push: true
          tags: arjunyadav17/excalidraw-be:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@54.161.214.83 -t "docker pull arjunyadav17/excalidraw-be:${{ github.sha }} && docker stop excalidraw-be && docker run --name excalidraw-be -d -e DATABASE_URL=${{ secrets.DATABASE_URL }} -p 5000:5000 arjunyadav17/excalidraw-be:${{ github.sha }}"
